#!/bin/bash

 set echo

 for dir in	geometry \
 		shared	\
 		coastline \
 		coastline2 \
 		stateboundary \
 		topography \
 		picking	\
 		contour	\
 		marchingCube	\
 		marchTetrahedron	\
 		view	\
 		control	\
 		translator	\
 		wrf	\
 		mpas	\
 		camse	\
 		pop	\
 		hdf	\
 		test	\
 		mpidemo	\
 		widget	\
 		windvector	\
 		trajectory	\
 		lic	\
		nclapp	\
 		main
 do
     cd $dir

     myqmake

     make

     cd ..
 done

 myqmake

 make

