#!/bin/bash

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Syntax: scriptName [-m|h|v|V]"
   echo "options:"
   echo "h     Print this Help."
   echo "m     model."
   echo "v     Verbose mode."
   echo "V     Print software version and exit."
   echo
}

# Set default model
model=ufs

############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts "h:m:vV" option; do
   case $option in
      h) # display Help
         Help
         exit 0;;
      m) # Enter a name
         model=$OPTARG
	 ;;
      v) # set verbose
         set -x
         ;;
      V) # print software version
         echo "StarViwer 0.0.1"
         exit 0;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit -1;;
   esac
done

echo "model: $model"

yamlfile="yamlfiles/${model}-config.yaml"

echo "yamlfile: $yamlfile"

# Create a temporary wildcard cookie file
 touch /scratch5/purged/Wei.Huang/tmp/xauth_wildcard
 xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /scratch5/purged/Wei.Huang/tmp/xauth_wildcard nmerge -

#for derecho
#export STARVIEWERHOME=/contrib/Wei.Huang/src/nv/starviewer
#export STARVIEWERHOME=/gpfs/csfs1/work/huangwei/nv/starviewer
#export CONTAINER_DIR=/gpfs/csfs1/work/huangwei/nv
#export CONTAINER_BINDINGS="-B /glade -B /gpfs -B /lustre"
#export RUNTIME_DIR=/gpfs/csfs1/work/huangwei/tmp/runtime-dir
#for ursa
 export STARVIEWERHOME=/scratch3/NAGAPE/epic/Wei.Huang/src/nv/starviewer
 export CONTAINER_DIR=${STARVIEWERHOME}
 export CONTAINER_BINDINGS="-B /scratch3 -B /scratch4 -B /scratch5"
 export RUNTIME_DIR=/scratch5/purged/Wei.Huang/tmp/runtime-dir

 export CONTAINER_SIF=${CONTAINER_DIR}/starviewer.sif

 if [ ! -d $RUNTIME_DIR ]; then
     mkdir -p $RUNTIME_DIR
     chmod 700 $RUNTIME_DIR
 fi

# 1. On the host terminal (e01g01), allow the connection
xhost +local:$(whoami)

# 2.1 Run Singularity with the auth file mapped to your actual home
#     on AMD GPU
#singularity exec --rocm --cleanenv \
# 2.2 Run Singularity with the auth file mapped to your actual home
#singularity exec --rocm --cleanenv \
#   --bind /tmp/.X11-unix:/tmp/.X11-unix \
#   --bind /dev/dri:/dev/dri \
#   --bind /dev/kfd:/dev/kfd \

singularity exec --rocm \
    --cleanenv \
    --hostname $(hostname) \
    --bind ${HOME}/.Xauthority:${HOME}/.Xauthority \
    --bind /scratch5/purged/Wei.Huang/tmp/xauth_wildcard:/tmp/xauth \
    -B /scratch3 -B /scratch4 -B /scratch5 -B /tmp \
    --env XAUTHORITY=/tmp/xauth \
    --env DISPLAY=$DISPLAY \
    --env XDG_RUNTIME_DIR=$RUNTIME_DIR \
    --env QT_X11_NO_MITSHM=1 \
    --env STARVIEWERHOME=${STARVIEWERHOME} \
    --env LIBGL_ALWAYS_INDIRECT=0 \
    "${CONTAINER_SIF}" \
    ${STARVIEWERHOME}/build/main/starviewer \
    -yaml "${yamlfile}"

#   -yaml config.yaml

#   --env MESA_LOADER_DRIVER_OVERRIDE=radeonsi \
#   --env LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/dri:$LD_LIBRARY_PATH \

 exit 0
#   gdb --args \
#   ${STARVIEWERHOME}/build/main/starviewer \

 xdg-open img_0015.png
