#!/bin/bash

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Syntax: scriptName [-m|h|v|V]"
   echo "options:"
   echo "h     Print this Help."
   echo "m     model."
   echo "v     Verbose mode."
   echo "V     Print software version and exit."
   echo
}

# Set default model
model=ufs

############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts "h:m:vV" option; do
   case $option in
      h) # display Help
         Help
         exit 0;;
      m) # Enter a name
         model=$OPTARG
	 ;;
      v) # set verbose
         set -x
         ;;
      V) # print software version
         echo "StarViwer 0.0.1"
         exit 0;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit -1;;
   esac
done

echo "model: $model"

yamlfile="yamlfiles/${model}-config.yaml"

echo "yamlfile: $yamlfile"

 export STARVIEWERHOME=/lustre/wei/nv/starviewer
 export CONTAINER_DIR=${STARVIEWERHOME}
 export CONTAINER_BINDINGS="-B /lustre"
 export RUNTIME_DIR=/lustre/wei/tmp/runtime-dir

 export CONTAINER_SIF=${CONTAINER_DIR}/starviewer.sif

 if [ ! -d $RUNTIME_DIR ]; then
     mkdir -p $RUNTIME_DIR
     chmod 700 $RUNTIME_DIR
 fi

singularity exec --cleanenv \
  --hostname $(hostname) \
  -B /lustre -B /tmp \
  --env QT_QPA_PLATFORM=offscreen \
  --env QT_OPENGL=software \
  --env QT_QUICK_BACKEND=software \
  --env LIBGL_ALWAYS_SOFTWARE=1 \
  --env GALLIUM_DRIVER=swrast \
  --env MESA_LOADER_DRIVER_OVERRIDE=swrast \
  --env STARVIEWERHOME=/lustre/wei/nv/starviewer \
  /lustre/wei/nv/starviewer/starviewer.sif \
  gdb --args \
  /lustre/wei/nv/starviewer/build/main/starviewer \
  -yaml yamlfiles/mpas-config.yaml

exit 0

#   gdb --args \
