#!/bin/csh -f

 set echo

 set datadir = /Users/weihuang/ncar_files/ncl/src/Python4NCL/doc/data

#nv ${datadir}/lfff00060000.grb
 nv ${datadir}/ruc.grb
#nv ${datadir}/dwd_gds10p.grb

#/glade/u/ncldev/data/grib1
#nv ${datadir}/p_RRRS48h_066

