#!/bin/bash
 set -x

#export STARVIEWERHOME=/contrib/Wei.Huang/src/nv/starviewer
#for derecho
#export STARVIEWERHOME=/gpfs/csfs1/work/huangwei/nv/starviewer
#export CONTAINER_DIR=/gpfs/csfs1/work/huangwei/nv
#export CONTAINER_BINDINGS="-B /glade -B /gpfs -B /lustre"
#export RUNTIME_DIR=/gpfs/csfs1/work/huangwei/tmp/runtime-dir
#for ursa
#export STARVIEWERHOME=/scratch4/NAGAPE/epic/Wei.Huang/src/nv/starviewer
 export STARVIEWERHOME=/scratch5/purged/Wei.Huang/src/nv/starviewer
 export CONTAINER_DIR=${STARVIEWERHOME}
 export CONTAINER_BINDINGS="-B /scratch3 -B /scratch4 -B /scratch5"
 export CONTAINER_SIF=${CONTAINER_DIR}/starviewer.sif
 export RUNTIME_DIR=/scratch5/purged/Wei.Huang/tmp/runtime-dir

 if [ ! -d $RUNTIME_DIR ]; then
     mkdir -p $RUNTIME_DIR
     chmod 700 $RUNTIME_DIR
 fi

#Run with --cleanenv to prevent host garbage from leaking in
 singularity exec --nv --cleanenv \
    --bind $HOME/.Xauthority:/root/.Xauthority \
    ${CONTAINER_BINDINGS} \
    --env STARVIEWERHOME=${STARVIEWERHOME} \
    --env XAUTHORITY=/root/.Xauthority \
    --env DISPLAY=$DISPLAY \
    --env XDG_RUNTIME_DIR=$RUNTIME_DIR \
    --env QT_X11_NO_MITSHM=1 \
    "${CONTAINER_SIF}" \
    ${STARVIEWERHOME}/build/main/starviewer -mpi mpi

#   gdb --args \
#   ${STARVIEWERHOME}/build/main/starviewer -mpi mpi

