#!/bin/bash
set -x

export STARVIWERHOME=/scratch4/NAGAPE/epic/Wei.Huang/src/nv/starviewer

# 1. Setup paths
export CONDA_PREFIX="/scratch4/NAGAPE/epic/Wei.Huang/conda-env/weienv"
export CONDA_LIB="$CONDA_PREFIX/lib"
export XDG_RUNTIME_DIR="/scratch4/NAGAPE/epic/Wei.Huang/tmp/runtime-Wei.Huang"
mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

# 2. Prioritize Conda and add NVIDIA system paths
# Note: We add the system nvidia paths to find the hardware drivers
export LD_LIBRARY_PATH="$CONDA_LIB:$LD_LIBRARY_PATH"

# 3. ABI Fix (Essential for the CXXABI error we saw earlier)
export LD_PRELOAD="$CONDA_LIB/libstdc++.so.6"

# 4. FIXING THE BLANK WINDOW (The "Hardware" approach)
# We UNSET the software override to let the GPU work
unset LIBGL_ALWAYS_SOFTWARE
export QT_X11_NO_MITSHM=1
export QT_QPA_PLATFORM=xcb

# Tell Qt to use the Desktop OpenGL implementation instead of EGL
#export QT_OPENGL_BACKEND=desktop

# 5. Tell the system to use the NVIDIA vendor for GLX
#export __GLX_VENDOR_LIBRARY_NAME=nvidia

# Replace section 4 and 5 in the script above with this if it fails:
#export LIBGL_ALWAYS_SOFTWARE=1
#export GALLIUM_DRIVER=llvmpipe
#export QT_XCB_GL_INTEGRATION=none

echo "Starting Starviewer on AMD mi300x Node..."
#gdb -batch -ex "run" -ex "bt" --args \
#/scratch4/NAGAPE/epic/Wei.Huang/src/nv/starviewer/build/main/starviewer -mpi mpi

/scratch4/NAGAPE/epic/Wei.Huang/src/nv/starviewer/build/main/starviewer -mpi mpi
