#!/bin/bash

 set -x

 cd /work2/noaa/epic/weihuang/nv/starviewer

 MODULE="hercules.gnu"

 if lsmod | grep -q "^$MODULE"; then
     echo "Module '$MODULE' is loaded."
 else
     module purge
     module use moduledir
     module load hercules.gnu 
 fi

#ldd /work2/noaa/epic/weihuang/nv/starviewer/build/main/starviewer | grep "not found"

#/work2/noaa/epic/weihuang/nv/starviewer/build/main/starviewer \
#	 -ufs /work2/noaa/epic/weihuang/nv/data/ufs-atm-history/gfs.t12z.atm.f000.nc

 export StarViewerHome=/work2/noaa/epic/weihuang/nv/starviewer
 export NV_HOME=/work2/noaa/epic/weihuang/nv/starviewer/src
 export LIBGL_ALWAYS_SOFTWARE=1
 export QT_QPA_PLATFORM=xcb

 gdb --args \
 /work2/noaa/epic/weihuang/nv/starviewer/build/main/starviewer\
 	-ufs /work2/noaa/epic/weihuang/nv/data/ufs-atm-history/gfs.t12z.atm.f000.nc
