#!/bin/sh

 LD_LIBRARY_PATH=/usr/local/lib/nv
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/local/lib
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/local/lib/gcc48
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/X11/lib
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/local/libexec/qt4/lib
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
 export LD_LIBRARY_PATH
#export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
 export DYLD_LIBRARY_PATH=/usr/local/lib/nv

 set -x

 nv -wrf -f /Users/weihuang/src/nv/data/STEP2015/wrfout/wrfout_d02_2015-07-15_00:00:00

 exit 0

