application:
  name: StarViewer
  model: eagleglobal
  version: 0.0.1

earth:
  name: data/earth.bmp

coastline:
  name: data/gshhg-shp-2.3.7/GSHHS_shp
  resolution: c

# 1. Define the variable using an anchor (&)
vars:
# base_dir: &data_path "/scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global"
  base_dir: &data_path "/scratch5/purged/Wei.Huang/src/EAGLE/run/wei_learning_main/vx/grid2grid/global/grids/forecast/20220203/12/024"

input:
  # 2. Reference the anchor so your script knows the directory
  directory: *data_path
  data:
    - "2t-heightAboveGround-0002.nc"
    - "10u-heightAboveGround-0010.nc"
    - "10v-heightAboveGround-0010.nc"
    - "t-isobaricInhPa-0850.nc"
    - "gh-isobaricInhPa-0500.nc"
    - "sp-surface.nc"
    - "u-isobaricInhPa-0250.nc"
    - "v-isobaricInhPa-0250.nc"
