application:
  name: StarViewer
  model: eagleglobal
  version: 0.0.1

earth:
  name: data/earth.bmp

coastline:
  name: data/gshhg-shp-2.3.7/GSHHS_shp
  resolution: c

input:
  data:
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/gh-isobaricInhPa-0500.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/t-isobaricInhPa-0850.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/10u-heightAboveGround-0010.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/10v-heightAboveGround-0010.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/2t-heightAboveGround-0002.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/gh-isobaricInhPa-0500.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/sp-surface.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/u-isobaricInhPa-0250.nc
    - /scratch5/purged/Wei.Huang/src/nv/data/eagle/forecast/global/v-isobaricInhPa-0250.nc
