application:
  name: StarViewer
  model: mpas
  version: 0.0.1

earth:
  name: data/earth.bmp

coastline:
  name: data/gshhg-shp-2.3.7/GSHHS_shp
  resolution: c

mpas:
  static:
    - /lustre/wei/nv/data/mpas/x1.10242.static.nc

  data:
    - /lustre/wei/nv/data/mpas/mpasjedi_tutorial2024_testdata/background/2018041418/mpasout.2018-04-15_02.00.00.nc
