application:
  name: StarViewer
  model: mpas
  version: 0.0.1

earth:
  name: data/earth.bmp

coastline:
  name: data/gshhg-shp-2.3.7/GSHHS_shp
  resolution: c

mpas:
  static:
    - /scratch3/NAGAPE/epic/Wei.Huang/src/nv/data/mpas/x1.2562.static.nc

  data:
    - /scratch5/purged/Wei.Huang/src/nv/data/gdas.t00z.atm.f006.nc
