application:
  name: StarViewer
  model: ufs
  version: 0.0.1

earth:
  name: /scratch5/purged/Wei.Huang/src/nv/starviewer/data/earth.bmp

coastline:
  name: /scratch5/purged/Wei.Huang/src/nv/starviewer/data/gshhg-shp-2.3.7/GSHHS_shp/c/GSHHS_c_L1.shp
  resolution: c

windvector:
  path: /scratch5/purged/Wei.Huang/src/nv/starviewer/colormaps/   # must have slash at the end.
  name: vector

input:
  data:
    - /scratch5/purged/Wei.Huang/src/nv/data/gdas.t00z.atm.f006.nc

animation:
  name: zRot
  interval: 400
