#!/bin/csh -f

 if($# > 0) then
    set flnm = $1
 else
    echo "Usage: $0 your-grb-filename"
    exit -1
 endif

 set os = `uname -s`

 if("Linux" == ${os}) then
     vglrun nv $flnm
 else
     nv $flnm
 endif

